### ISSUE TITLE
TransactionExecutor.execute can't handle List<IonValue> arguments

### ISSUE THREAD

**Issue by deionut** [awslabs/amazon-qldb-driver-java#34]
The code below fails with exception:
  	
```
    	IonLoader ionLoader = IonSystemBuilder.standard().build().newLoader();
    	IonValue rootVal = ionLoader.load("[{\"key1\":\"val1\"},{\"key2\":\"val2\"}]");
    	IonList ionList = (IonList)((IonDatagram) rootVal).get(0); 	

    	try
    	{
            mQldbDriver.execute(txn -> {
                final String insertIntoQuery = String.format("INSERT INTO %s ?", aTableName);
                final Result result = txn.execute(insertIntoQuery, ionList);
                mLog.info(String.format("addErsGenHashes('%s'): OK, result: %s", aTableName, result));
            });
    	}
    	catch(Exception ex)
    	{
    		ex.printStackTrace();
    		mLog.log(Level.SEVERE, String.format("failed to insert gen hashes into table '%s', exception thrown: %s", aTableName, ex.getMessage()));
    		return false;
    	}

```
The exception throw is:
software.amazon.awssdk.services.qldbsession.model.BadRequestException: Query expects 1 parameters, but statement has 2 (Service: QldbSession, Status Code: 400, Request ID: JOzfOAHckjp4S6IKIBPDsH, Extended Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:123)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:79)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:59)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:189)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:121)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:147)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:101)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
	at software.amazon.awssdk.services.qldbsession.DefaultQldbSessionClient.sendCommand(DefaultQldbSessionClient.java:108)
	at software.amazon.qldb.Session.send(Session.java:271)
	at software.amazon.qldb.Session.sendExecute(Session.java:221)
	at software.amazon.qldb.Transaction.execute(Transaction.java:154)
	at software.amazon.qldb.TransactionExecutor.execute(TransactionExecutor.java:71)
	at com.xxx.QLErs.lambda$2(QLErs.java:383)
	at software.amazon.qldb.QldbDriverImpl.lambda$execute$0(QldbDriverImpl.java:121)
	at software.amazon.qldb.QldbSession.execute(QldbSession.java:82)
	at software.amazon.qldb.QldbDriverImpl.execute(QldbDriverImpl.java:146)
	at software.amazon.qldb.QldbDriverImpl.execute(QldbDriverImpl.java:120)
	at software.amazon.qldb.QldbDriverImpl.execute(QldbDriverImpl.java:115)
	at com.xxx.QLErs.addErsGenHashes(QLErs.java:381)
	at QLErsTest.addErsGenHashes(QLErsTest.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Oct 30, 2020 6:45:00 PM com.xxx.QLErs addErsGenHashes
SEVERE: failed to insert gen hashes into table 'xxx_table', exception thrown: Query expects 1 parameters, but statement has 2 (Service: QldbSession, Status Code: 400, Request ID: JOzfOAHckjp4S6IKIBPDsH, Extended Request ID: null)

However if I modify the code above to iterate through the IonList and add each IonValue by itself it works (but I guess it is less eficient...):

```
    	IonLoader ionLoader = IonSystemBuilder.standard().build().newLoader();
    	IonValue rootVal = ionLoader.load("[{\"key1\":\"val1\"},{\"key2\":\"val2\"}]");
    	IonList ionList = (IonList)((IonDatagram) rootVal).get(0); 	

    	for(final IonValue crtIonVal : ionList)
    	{
        	try
        	{
                mQldbDriver.execute(txn -> {
                    final String insertIntoQuery = String.format("INSERT INTO %s ?", aTableName);
                    final Result result = txn.execute(insertIntoQuery, crtIonVal);
                    mLog.info(String.format("addErsGenHashes('%s'): OK, result: %s", aTableName, result));
                });
        	}
        	catch(Exception ex)
        	{
        		ex.printStackTrace();
        		mLog.log(Level.SEVERE, String.format("failed to insert gen hashes into table '%s', exception thrown: %s", aTableName, ex.getMessage()));
        		return false;
        	}
    	}

```

**Comment by marcbowes** [comment]
> Query expects 1 parameters, but statement has 2

Is there a chance your table name has a question mark in it? I see you log the table name out but I'm guessing you replaced the actual table name with 'xxx_table'.

**Comment by deionut** [comment]
Table name does not contain a question mark, it’s only alpha-numeric characters in the form xxxxx4_table

**Comment by saumehta9** [comment]
@deionut  

I see that you are trying to insert a list of structs.

Can you try 
`final String insertIntoQuery = String.format("INSERT INTO %s <<? ,?>>", aTableName);`

**Comment by deionut** [comment]
@saumehta9

Thanks, this solved the issue!

Regards

**Comment by deionut** [comment]
I works for a hardcoded initial JSON of just 2 entries, as in the example above; I tried running the above query strings (with 2 question marks) with a JSON array that had 6 entries and it failed with this exception: 

Query expects 2 parameters, but statement has 6 (Service: QldbSession, Status Code: 400, Request ID: A8712G3JNgHLJC4TjE2U8u, Extended Request ID: null)

Thus (I guess) the number of question marks in the query string (e.g. String.format("INSERT INTO %s <<? ,?>>" ) has to match the number of entries in the JSON array. Do I have to format the query string to painfully pair each ? or is there a simpler, more direct and with lesser questions way ????? (how many ? should this question have :)))) ?????

**Comment by aurghob33** [comment]
Hi @deionut,

I’m assuming you’re using the 2.x version of the Java Driver.

Can you try the below snippet instead and let me know if it works?
This snippet will only need one "?" here.
```
import com.amazon.ion.IonSystem;
import com.amazon.ion.system.IonSystemBuilder;

mQldbDriver.execute(txn -> {
	final String insertIntoQuery = String.format("INSERT INTO %s ?", aTableName);
	IonValue rootVal = ionLoader.load("[{\"key1\":\"val1\"},{\"key2\":\"val2\"}]");
	final Result result = txn.execute(query, rootVal);
mLog.info(String.format("addErsGenHashes('%s'): OK, result: %s", aTableName, result));
        });
}
```

Please note that the maximum number of documents that can be inserted is documented [here](https://docs.aws.amazon.com/qldb/latest/developerguide/limits.html) and currently is at 40.
If IonList must be used, multiple "?" will be required here.

**Comment by deionut** [comment]
Hi @aurghob33,

Your code above works. Treating the input json as a single IonValue instead of a list works with just 1 question mark in the query string. I tested the input json array with 41 entries and it fails but it works with 40. The issue now is how to split the root list IonValue into max 40 entries sublists. If you have any sample code that could direct me it would be great, but this issue can be closed.

Thanks & regards.
